version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-cadastros
    restart: always
    environment:
      POSTGRES_DB: cadastros_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: