services:
  # Serviço do Banco de Dados Relacional para Clientes
  postgres:
    image: postgres:15
    container_name: postgres-cadastros
    restart: always
    environment:
      POSTGRES_DB: cadastros_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do Banco de Dados NoSQL para Produtos
  mongo:
    image: mongo:6.0
    container_name: mongo-cadastros
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Serviço de Mensageria (Pub/Sub) e Cache
  redis:
    image: redis:7
    container_name: redis-pubsub
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# Definição dos volumes para persistir os dados
volumes:
  postgres_data:
  mongo_data:
  redis_data: